# Generated by Django 6.0 on 2026-06-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bidon_stock_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='material',
            field=models.CharField(choices=[('PET', 'Plástico'), ('POL', 'Policarbonato'), ('N/A', 'No aplica')], default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='retornable',
            field=models.CharField(choices=[('RET', 'Retornable'), ('NO_RET', 'No Retornable'), ('N/A', 'No aplica')], default='N/A', max_length=10),
        ),
        migrations.DeleteModel(
            name='Bidon',
        ),
    ]
