# Generated by Django 6.0 on 2026-06-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=20),
        ),
    ]
